sistemasai/src/com/agrosolutions/sai/model/Tecnico.java
package com.agrosolutions.sai.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Where;
import org.hibernate.envers.Audited;
import org.primefaces.model.SortOrder;

@Entity
@SequenceGenerator(name = "entity_sequence", sequenceName = "sq_Tecnico", allocationSize = 1)
@Table
@Audited
@NamedQueries({
	@NamedQuery(name = "Tecnico.excluir", 
			   query = "DELETE FROM Tecnico t WHERE t.id = :pId"), 			  
	@NamedQuery(name = "Tecnico.pesquisar", 
			   query = "SELECT t FROM Tecnico t WHERE t.distrito IN (:pDistrito) ORDER BY t.nome ASC")
   })
public class Tecnico extends Model implements Serializable {

	private static final long serialVersionUID = 7627003472606016615L;
	private String nome;
	private String foto;
	private String endereco;
	private String cidade;
	private String cep;
	private String uf;
	private String telefoneContato;
	private String celular;
	private OperadoraCelular operadora;
	private Escolaridade escolaridade;
	@Column(length=800)
	private String observacao;
	
	@Temporal(TemporalType.DATE)
	private Date dataCadastro;
	@Where(clause = "dataInatividade is null") 
	@Temporal(TemporalType.DATE)
	private Date dataInatividade;

	@ManyToOne
	private Distrito distrito;

	@Transient
	private String sortField;
	@Transient
	private SortOrder sortOrder;
	
	@OneToOne
	private Usuario usuario;

	public Tecnico() {
		super();
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getEndereco() {
		return endereco;
	}
	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}
	public String getCidade() {
		return cidade;
	}
	public void setCidade(String cidade) {
		this.cidade = cidade;
	}
	public String getCep() {
		return cep;
	}
	public void setCep(String cep) {
		this.cep = cep;
	}
	public String getUf() {
		return uf;
	}
	public void setUf(String uf) {
		this.uf = uf;
	}
	public String getTelefoneContato() {
		return telefoneContato;
	}
	public void setTelefoneContato(String telefoneContato) {
		this.telefoneContato = telefoneContato;
	}
	public String getCelular() {
		return celular;
	}
	public void setCelular(String celular) {
		this.celular = celular;
	}
	public OperadoraCelular getOperadora() {
		return operadora;
	}
	public void setOperadora(OperadoraCelular operadora) {
		this.operadora = operadora;
	}
	public Escolaridade getEscolaridade() {
		return escolaridade;
	}
	public void setEscolaridade(Escolaridade escolaridade) {
		this.escolaridade = escolaridade;
	}
	public String getObservacao() {
		return observacao;
	}
	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}
	public String getFoto() {
		return foto;
	}
	public void setFoto(String foto) {
		this.foto = foto;
	}
	public Date getDataCadastro() {
		return dataCadastro;
	}
	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}
	public Date getDataInatividade() {
		return dataInatividade;
	}
	public void setDataInatividade(Date dataInatividade) {
		this.dataInatividade = dataInatividade;
	}
	public Distrito getDistrito() {
		return distrito;
	}
	public void setDistrito(Distrito distrito) {
		this.distrito = distrito;
	}
	public String getSortField() {
		return sortField;
	}
	public void setSortField(String sortField) {
		this.sortField = sortField;
	}
	public Usuario getUsuario() {
		return usuario;
	}
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	public void setSortOrder(SortOrder ascending) {
		this.sortOrder = ascending;
	}
	public SortOrder getSortOrder() {
		return sortOrder;
	}
}

sistemasai/src/com/agrosolutions/sai/view/CadastrarTecnicoBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;
import java.util.List;

import javax.faces.event.ActionEvent;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Distrito;
import com.agrosolutions.sai.model.Escolaridade;
import com.agrosolutions.sai.model.OperadoraCelular;
import com.agrosolutions.sai.model.Perfil;
import com.agrosolutions.sai.model.Tecnico;
import com.agrosolutions.sai.model.TipoPerfil;
import com.agrosolutions.sai.model.Usuario;
import com.agrosolutions.sai.service.PerfilService;
import com.agrosolutions.sai.service.TecnicoService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Cadastrar Tecnico
* 
* @since   : Jan 11, 2012, 03:23:20 AM
* @author  : raphael.ferreira@ivia.com.br
*/	

@Component("cadastrarTecnicoBean")
@Scope("session")
public class CadastrarTecnicoBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = -3456232235861349235L;

	public static Logger logger = Logger.getLogger(CadastrarTecnicoBean.class);

	public static final String MSG_TITULO = "Cadastro de Tecnico";

	@Autowired
	private TecnicoService tecnicoService;
	@Autowired
	private PerfilService perfilService;
	
	private Tecnico tecnico;
	private List<Distrito> distritos;
	private boolean multiDistrito;
	private List<Perfil> perfis;
	private String operacao;
	
	public void carregarDadosIniciais() {
		operacao = getOperacao();
		tecnico = getTecnico();
		
		if (operacao.equals("NOVO") && tecnico == null) {
			tecnico = new Tecnico();
			tecnico.setUsuario(new Usuario());
			tecnico.getUsuario().setAtivo(true);
			tecnico.getUsuario().setDistritos(super.getDistritosPesquisa());
		}
		if ((operacao.equals("ALTERAR") || operacao.equals("VER")) && tecnico != null) {
			if(tecnico.getUsuario().getConfirmarEmail() == null) {
				tecnico.getUsuario().setConfirmarEmail(tecnico.getUsuario().getEmail());
				tecnico.getUsuario().setConfirmarSenha(tecnico.getUsuario().getPassword());
			}
		}
		if (operacao.equals("ALTERAR") || operacao.equals("NOVO")){		
			distritos = super.getDistritosPesquisa();
			perfis = perfilService.porTipo(TipoPerfil.Tecnico);
		}
	}
	
	public void gravar(ActionEvent actionEvent) {
		if (operacao.equals("NOVO")) {
			tecnico = tecnicoService.salvar(tecnico);
			tecnico = null;
			infoMsg(ResourceBundle.getMessage("tecnicoSalvar")+ ".", MSG_TITULO);
		}else{
			tecnico = tecnicoService.editar(tecnico);
			infoMsg(ResourceBundle.getMessage("tecnicoAlterar")+ ".", MSG_TITULO);
		}	
    }

	public String voltar() {
		return "consultarTecnico?faces-redirect=true";
	}
	
	public Escolaridade[] getEscolaridades() {
		return Escolaridade.values();
	}

	public OperadoraCelular[] getOperadoras() {
		return OperadoraCelular.values();
	}

	public Tecnico getTecnico() {
		if (tecnico == null) {
			tecnico = (Tecnico) getFlashScope().get("tecnico");
		}
		return tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
		getFlashScope().put("tecnico", tecnico);
	}

	public List<Distrito> getDistritos() {
		return distritos;
	}

	public void setDistritos(List<Distrito> regioes) {
		this.distritos = regioes;
	}

	public boolean isMultiDistrito() {
		return multiDistrito;
	}

	public void setMultiDistrito(boolean multiDistrito) {
		this.multiDistrito = multiDistrito;
	}

	public List<Perfil> getPerfis() {
		return perfis;
	}

	public void setPerfis(List<Perfil> perfis) {
		this.perfis = perfis;
	}

	public String getOperacao() {
		if (operacao == null) {
			operacao = (String) getFlashScope().get("operacao");
		}
		return operacao;
	}

	public void setOperacao(String operacao) {
		this.operacao = operacao;
		getFlashScope().put("operacao", operacao);
	}
}

sistemasai/src/com/agrosolutions/sai/view/ConsultarTecnicoBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.faces.model.SelectItem;

import org.apache.log4j.Logger;
import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Distrito;
import com.agrosolutions.sai.model.Escolaridade;
import com.agrosolutions.sai.model.Tecnico;
import com.agrosolutions.sai.service.TecnicoService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Consultar Tecnico
* 
* @since   : Jan 11, 2012, 02:23:20 AM
* @author  : raphael.ferreira@ivia.com.br
*/

@Component("consultarTecnicoBean")
@Scope("view")
public class ConsultarTecnicoBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = -5188037621690407211L;

	public static Logger logger = Logger.getLogger(ConsultarTecnicoBean.class);

	public static final String MSG_TITULO = "Consultar Tecnicos";

	@Autowired
	private TecnicoService tecnicoService;
	
	private LazyDataModel<Tecnico> tecnicos;
	private Tecnico tecnicoSelecionado;
	private SelectItem[] distritos;
	private boolean multiDistrito;
	private Tecnico tecnicoBusca;
	
	public void carregarDadosIniciais() {
		
		if (tecnicoBusca == null){
			tecnicoBusca = new Tecnico();
			tecnicoBusca.setSortField("nome");
			tecnicoBusca.setSortOrder(SortOrder.ASCENDING);
			consultar();
		}
		
		List<Distrito> distritos = getUsuarioLogado().getDistritos();
		this.distritos = criarFiltroDistritos(distritos);
	}
	
	public void consultar(){
		tecnicos = new LazyDataModel<Tecnico>() {

			private static final long serialVersionUID = -4516421974865107877L;

			@Override
			public List<Tecnico> load(int first, int pageSize, String sortField,
					SortOrder sortOrder, Map<String, String> filters) {
				List<Tecnico> tecnicos = new ArrayList<Tecnico>();

				if(sortField == null){
					sortField = "nome";
					sortOrder = SortOrder.ASCENDING;
				}
		        
				tecnicoBusca.setSortField(sortField);
				tecnicoBusca.setSortOrder(sortOrder);
				
				tecnicos = tecnicoService.pesquisar(tecnicoBusca, first, pageSize);
				
				return tecnicos;
			}
		};
		int quantidade = tecnicoService.quantidade(tecnicoBusca);
	    tecnicos.setRowCount(quantidade==0?1:quantidade);
	}
	
	private SelectItem[] criarFiltroDistritos(List<Distrito> distritos)  {  
        SelectItem[] options = new SelectItem[distritos.size() + 1];  
  
        options[0] = new SelectItem("", "Todas");  
        for(int i = 0; i < distritos.size(); i++) {  
            options[i + 1] = new SelectItem(distritos.get(i).getNome(), distritos.get(i).getNome());  
        }  
  
        return options;  
    }  

	public String cadastro() {
		return "cadastrarTecnico?faces-redirect=true";
	}

	public void excluir(){
	    tecnicoService.excluir(tecnicoSelecionado);
	    setTecnicos(null);
		infoMsg(ResourceBundle.getMessage("tecnicoExcluir")+ ".", MSG_TITULO);
	}

	public SelectItem[] getDistritos() {
		return distritos;
	}

	public void setDistritos(SelectItem[] distritos) {
		this.distritos = distritos;
	}

	public boolean isMultiDistrito() {
		return multiDistrito;
	}

	public void setMultiDistrito(boolean multiDistrito) {
		this.multiDistrito = multiDistrito;
	}

	public Tecnico getTecnicoSelecionado() {
		return tecnicoSelecionado;
	}

	public void setTecnicoSelecionado(Tecnico tecnicoSelecionado) {
		this.tecnicoSelecionado = tecnicoSelecionado;
	}

	public void setTecnicos(LazyDataModel<Tecnico> tecnicos) {
		this.tecnicos = tecnicos;
	}

	public LazyDataModel<Tecnico> getTecnicos() {
		return tecnicos;
	}

	public void setTecnicoBusca(Tecnico tecnicoBusca) {
		this.tecnicoBusca = tecnicoBusca;
	}

	public Tecnico getTecnicoBusca() {
		return tecnicoBusca;
	}
	public Escolaridade[] getEscolaridades(){
		return Escolaridade.values();
	}
}

sistemasai/WebContent/paginas/tecnico/cadastrarTecnico.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="../../WEB-INF/templates/page.xhtml"
		xmlns="http://www.w3.org/1999/xhtml"     
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:c="http://java.sun.com/jsp/jstl/core"
	  	xmlns:p="http://primefaces.org/ui" >
		
	<ui:define name="content">
		
		<f:metadata>
		   <f:event type="preRenderView" listener="#{cadastrarTecnicoBean.carregarDadosIniciais}" />	
		</f:metadata>			
		
		<h:form id="frmCadastrarTecnico" styleClass="formularios box-border" prependId="false">
			<p:messages showDetail="false" autoUpdate="true" for="textOnly" display="text"/>
			<div class="bc cinzaclaro barra">
        		<div class="titulo" >
					#{bundle.cadastroTecnico}
				</div>
				<div class="botoes">
					<p:commandButton id="btSalvar" actionListener="#{cadastrarTecnicoBean.gravar}" value="#{bundle.salvar}" styleClass="btn primary" update=":frmCadastrarTecnico" process="@form" rendered="#{cadastrarTecnicoBean.operacao ne 'VER'}"/>
					<p:commandButton id="btVoltar" value="#{bundle.voltar}" action="#{cadastrarTecnicoBean.voltar}" styleClass="btn success" immediate="true" />
				</div>
			</div>	
			<div class="b2 cinzaclaro"></div>
			<div class="b1 cinzaclaro"></div>
			<br />
			<div class="row cadastro">		
				<div class="col-direita">
					<div class="row">
						<p:outputPanel rendered="#{cadastrarTecnicoBean.multiDistrito}">
							<div class="span2 clear">
								<label for="distrito" class="block"><b>#{bundle.distrito}:</b></label>							
								<h:selectOneMenu id="distrito" value="#{cadastrarTecnicoBean.tecnico.distrito}" converter="distritoConverter" title="#{bundle.selecioneDistritoPertenceTecnico}" style="width: 89px;" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}" >  
			            			<f:selectItems var="distrito" itemLabel="#{distrito.nome}" itemValue="#{distrito}" value="#{cadastrarTecnicoBean.distritos}"  />
				        		</h:selectOneMenu>							
							</div>
						</p:outputPanel>
	
						<div class="span2">
							<label for="nome"><b>#{bundle.nome}:</b></label><label class="label-required">*</label>
							<p:inputText styleClass="span12 block" required="true" id="nome" requiredMessage="#{bundle.nomeObrigatorio}" title="#{bundle.nome}" maxlength="255" value="#{cadastrarTecnicoBean.tecnico.nome}" size="113" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}"/>
						</div>
						<div class="span2 clear">
							<label for="login">#{bundle.login}:</label><label class="label-required">*</label>
							<p:inputText styleClass="span6 block" id="login" required="true" requiredMessage="#{bundle.loginObrigatorio}" value="#{cadastrarTecnicoBean.tecnico.usuario.username}" size="36" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}"/>
						</div>
						
						<div class="span2">
							<p:outputPanel rendered="#{cadastrarTecnicoBean.operacao eq 'NOVO'}">
								<label for="senha" class="block">#{bundle.senha}:</label>
								<p:password id="senha" value="#{cadastrarTecnicoBean.tecnico.usuario.password}" size="32" styleClass="span5"/>
							</p:outputPanel>  
						</div>
	
						<div class="span2">
							<p:outputPanel rendered="#{cadastrarTecnicoBean.operacao eq 'NOVO'}">
								<label for="confirmarSenha" class="block">#{bundle.confirmarSenha}:</label>
								<p:password id="confirmarSenha" value="#{cadastrarTecnicoBean.tecnico.usuario.confirmarSenha}" feedback="false" size="32"  styleClass="span5"/>  							
							</p:outputPanel>  
						</div>
	
						<div class="span2 clear">
							<label for="perfil" class="block">#{bundle.perfil}:</label>							
							<h:selectOneMenu id="perfil" value="#{cadastrarTecnicoBean.tecnico.usuario.perfil}" converter="perfilConverter" title="Selecione um perfil" style="width: 189px;" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}">  
		            			<f:selectItems var="perfil" itemLabel="#{perfil.descricao}" itemValue="#{perfil}" value="#{cadastrarTecnicoBean.perfis}"  />
			        		</h:selectOneMenu>							
						</div>
						
						<div class="span2">
							<label for="email" class="block">#{bundle.email}:</label>
							<p:inputText id="email" value="#{cadastrarTecnicoBean.tecnico.usuario.email}" size="32" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}"/>  
						</div>
	
						<div class="span2">
							<p:outputPanel rendered="#{cadastrarTecnicoBean.operacao ne 'VER'}">
								<label for="confirmarEmail" class="block">#{bundle.confirmarEmail}:</label>
								<p:inputText id="confirmarEmail" value="#{cadastrarTecnicoBean.tecnico.usuario.confirmarEmail}" size="32"/>
							</p:outputPanel>  							
						</div>
	
						<div class="span2 clear">
							<label for="endereco" class="block">#{bundle.endereco}:</label>
							<p:inputText id="endereco" maxlength="255" value="#{cadastrarTecnicoBean.tecnico.endereco}" size="51"  styleClass="span8" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}"/>							
						</div>
	
						<div class="span2">
							<label for="cidade" class="block">#{bundle.cidade}:</label>
							<p:inputText id="cidade" maxlength="255" value="#{cadastrarTecnicoBean.tecnico.cidade}" size="30" styleClass="span4" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}"/>							
						</div>
	
						<div class="span2">
							<label for="cep" class="block"><b>#{bundle.cep}:</b></label>
							<p:inputMask id="cep"  maxlength="255" value="#{cadastrarTecnicoBean.tecnico.cep}" mask="99.999-999" size="10" styleClass="span3" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}"/>							
						</div>
	
						<div class="span2">
							<label for="uf" class="block"><b>#{bundle.uf}:</b></label>
							<p:inputMask id="uf"  maxlength="255" value="#{cadastrarTecnicoBean.tecnico.uf}" mask="aa?" size="3" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}"/>							
						</div>
	
						<div class="span2 clear">
							<label for="telefoneContato" class="block"><b>#{bundle.telContato}:</b></label>
							<p:inputMask id="telefoneContato" maxlength="255" value="#{cadastrarTecnicoBean.tecnico.telefoneContato}" mask="(99)9999-9999" size="38" styleClass="span3" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}"/>							
						</div>
	
						<div class="span2">
							<label for="celular" class="block"><b>#{bundle.celular}:</b></label>
							<p:inputMask id="celular" maxlength="255" value="#{cadastrarTecnicoBean.tecnico.celular}" mask="(99)99999-9999" size="38" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}"/>							
						</div>
		
						<div class="span2">
							<label for="operadora" class="block"><b>#{bundle.operadora}:</b></label>							
							<h:selectOneMenu id="operadora" value="#{cadastrarTecnicoBean.tecnico.operadora}" title="#{bundle.selecioneOperadora}" style="width: 173px;" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}">  
		            			<f:selectItems var="tipo" itemLabel="#{tipo.descricao}" itemValue="#{tipo}" value="#{cadastrarTecnicoBean.operadoras}"  />
			        		</h:selectOneMenu>							
						</div>
		
						<div class="span2 ">
							<label for="escolaridade" class="block"><b>#{bundle.escolaridade}:</b></label>							
							<h:selectOneMenu  id="escolaridade" value="#{cadastrarTecnicoBean.tecnico.escolaridade}" title="#{bundle.selecioneEscolaridade}" style="width: 300px;" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}">  
		            			<f:selectItems var="tipo" itemLabel="#{tipo.descricao}" itemValue="#{tipo}" value="#{cadastrarTecnicoBean.escolaridades}"  />
			        		</h:selectOneMenu>							
						</div>
						<div class="span2 clear">
							<label for="observacao" class="block"><b>#{bundle.observacao}:</b></label>
							<p:inputTextarea id="observacao" cols="113" rows="2" autoResize="false" maxlength="800" style="width: 910px;" value="#{cadastrarTecnicoBean.tecnico.observacao}" disabled="#{cadastrarTecnicoBean.operacao eq 'VER'}"/>							
						</div>
					</div>
				</div>
			</div>				
		</h:form>
	</ui:define>
</ui:composition>