sistemasai/src/com/agrosolutions/sai/view/CadastrarAreaBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;
import java.util.List;

import javax.faces.event.ActionEvent;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Area;
import com.agrosolutions.sai.model.Distrito;
import com.agrosolutions.sai.service.AreaService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Cadastrar Area
* 
* @since   : Jan 06, 2012, 15:00:20 AM
* @author  : raphael.ferreira@ivia.com.br
*/

@Component("cadastrarAreaBean")
@Scope("session")
public class CadastrarAreaBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = -3028443469794245093L;

	public static Logger logger = Logger.getLogger(CadastrarAreaBean.class);

	public static final String MSG_TITULO = "Cadastro de área";

	@Autowired
	private AreaService areaService;
	
	private Area area;
	private List<Distrito> distritos;
	private Boolean multiDistrito;
	private String operacao;

	public void carregarDadosIniciais() {
		operacao = getOperacao();
		area = getArea();
		
		if (operacao.equals("NOVO") && area == null) {
			area = new Area();
			if (getUsuarioLogado().getDistritos().size() == 1) {
				area.setDistrito(getUsuarioLogado().getDistritos().get(0));
				multiDistrito = false;
			}else{
				multiDistrito = true;
				distritos = getUsuarioLogado().getDistritos();
			}
		}
	}
	
	public void gravar(ActionEvent actionEvent) {
		area = areaService.salvar(area); 
		if (operacao.equals("NOVO")) {
			area = null;
			infoMsg(ResourceBundle.getMessage("areaSalvar")+ ".", MSG_TITULO);
		}else{
			infoMsg(ResourceBundle.getMessage("areaAlterar")+ ".", MSG_TITULO);
		}
    }

	public String voltar() {
		return "consultarArea?faces-redirect=true";
	}

	public Area getArea() {
		if (area == null) {
			area = (Area) getFlashScope().get("area");
		}
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
		getFlashScope().put("area", area);
	}

	public Boolean getMultiDistrito() {
		return multiDistrito;
	}

	public void setMultiDistrito(Boolean multiDistrito) {
		this.multiDistrito = multiDistrito;
	}

	public List<Distrito> getDistritos() {
		return distritos;
	}

	public void setDistritos(List<Distrito> distritos) {
		this.distritos = distritos;
	}
	public String getOperacao() {
		if (operacao == null) {
			operacao = (String) getFlashScope().get("operacao");
		}
		return operacao;
	}

	public void setOperacao(String operacao) {
		this.operacao = operacao;
		getFlashScope().put("operacao", operacao);
	}
}

sistemasai/src/com/agrosolutions/sai/view/CadastrarClimaBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.faces.event.ActionEvent;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Area;
import com.agrosolutions.sai.model.Clima;
import com.agrosolutions.sai.service.ClimaService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Cadastrar Clima
* 
* @since   : Mar 09, 2012, 20:23:20 PM
* @author  : raphael.ferreira@ivia.com.br
*/

@Component("cadastrarClimaBean")
@Scope("session")
public class CadastrarClimaBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = 3055712674382182387L;

	public static Logger logger = Logger.getLogger(CadastrarClimaBean.class);

	@Autowired
	private ClimaService climaService;
	
	private Area area;
	private Clima clima;
	private String operacao;
	private BigDecimal altitude;
	
	public void carregarDadosIniciais() {
		operacao = getOperacao();
		area = getArea();
		
		if (operacao.equals("NOVO") &&clima == null) {
			clima = new Clima(new Date(), area, null);
		}
		
	}
	
	public void gravar(ActionEvent actionEvent) {
		clima = climaService.prepararClimaCalcularEto(clima);
		clima = climaService.salvar(clima);
		if (operacao.equals("NOVO")) {
			clima = null;
			infoMsg(ResourceBundle.getMessage("climaSalvar")+ ".", null);
		}else{
			infoMsg(ResourceBundle.getMessage("climaAlterar")+ ".", null);
		}
	}
	
	public String voltar() {
		return "consultarClima?faces-redirect=true";
	}
	
	public Area getArea() {
		if (area == null) {
			area = (Area) getFlashScope().get("area");
		}
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
		getFlashScope().put("area", area);
	}

	public String getOperacao() {
		if (operacao == null) {
			operacao = (String) getFlashScope().get("operacao");
		}
		return operacao;
	}

	public void setOperacao(String operacao) {
		this.operacao = operacao;
		getFlashScope().put("operacao", operacao);
	}

	public Clima getClima() {
		return clima;
	}

	public void setClima(Clima clima) {
		this.clima = clima;
	}

	public BigDecimal getAltitude() {
		return altitude;
	}

	public void setAltitude(BigDecimal altitude) {
		this.altitude = altitude;
	}
}

sistemasai/src/com/agrosolutions/sai/view/CadastrarDistritoBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;

import javax.faces.event.ActionEvent;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Distrito;
import com.agrosolutions.sai.service.DistritoService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Cadastrar Distrito
* 
* @since   : Jan 06, 2012, 15:00:20 AM
* @author  : raphael.ferreira@ivia.com.br
*/

@Component("cadastrarDistritoBean")
@Scope("session")
public class CadastrarDistritoBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = 4966644135386030844L;

	public static Logger logger = Logger.getLogger(CadastrarDistritoBean.class);

	public static final String MSG_TITULO = "Cadastro de Distrito";

	@Autowired
	private DistritoService distritoService;
	
	private Distrito distrito;
	private String operacao;

	public void carregarDadosIniciais() {
		operacao = getOperacao();
		distrito = getDistrito();
		
		if (operacao.equals("NOVO") && distrito == null) {
			setDistrito(new Distrito());
		}
	}
	
	public void gravar(ActionEvent actionEvent) {
		distrito = distritoService.salvar(distrito); 
		if (operacao.equals("NOVO")) {
		distrito = null;
			infoMsg(ResourceBundle.getMessage("distritoSalvar")+ ".", MSG_TITULO);
		}else{
			infoMsg(ResourceBundle.getMessage("distritoAlterar")+ ".", MSG_TITULO);
		}
	}
	public String voltar() {
		return "consultarDistrito?faces-redirect=true";
	}

	public Distrito getDistrito() {
		if (distrito == null) {
			distrito = (Distrito) getFlashScope().get("distrito");
		}
		return distrito;
	}

	public void setDistrito(Distrito distrito) {
		this.distrito = distrito;
		getFlashScope().put("distrito", distrito);
	}
	
	public String getOperacao() {
		if (operacao == null) {
			operacao = (String) getFlashScope().get("operacao");
		}
		return operacao;
	}

	public void setOperacao(String operacao) {
		this.operacao = operacao;
		getFlashScope().put("operacao", operacao);
	}
}

sistemasai/src/com/agrosolutions/sai/view/CadastrarEstacaoBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.event.ActionEvent;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Area;
import com.agrosolutions.sai.model.Distrito;
import com.agrosolutions.sai.model.Estacao;
import com.agrosolutions.sai.service.AreaService;
import com.agrosolutions.sai.service.DistritoService;
import com.agrosolutions.sai.service.EstacaoService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Cadastrar Estacao
* 
* @since   : Mar 01, 2012, 15:00:20 AM
* @author  : raphael.ferreira@ivia.com.br
*/

@Component("cadastrarEstacaoBean")
@Scope("session")
public class CadastrarEstacaoBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = 4499512157516611325L;

	public static Logger logger = Logger.getLogger(CadastrarEstacaoBean.class);

	public static final String MSG_TITULO = "Cadastro de Estação";

	@Autowired
	private EstacaoService estacaoService;
	@Autowired
	private DistritoService distritoService;
	@Autowired
	private AreaService areaService;
	
	private Estacao estacao;
	private List<Distrito> distritos = new ArrayList<Distrito>();
	private Boolean multiDistrito;
	private List<Area> areas;
	private Area[] areasSelecionadas;
	private String operacao;

	public void carregarDadosIniciais() {
		operacao = getOperacao();
		estacao = getEstacao();
		distritos = getDistritosPesquisa();

		if (operacao.equals("NOVO") && estacao == null) {
			estacao = new Estacao();
			if ( multidistrito ) {
				estacao.setDistrito( getUsuarioLogado().getDistritoPadrao() );
			} else {
				estacao.setDistrito(getUsuarioLogado().getDistritos().get(0));
			}
		}
		
		if ((operacao.equals("ALTERAR") || operacao.equals("VER")) && estacao != null) {
			ArrayList<Distrito> dists = new ArrayList<Distrito>();
			dists.add(estacao.getDistrito());
			areas = areaService.pesquisar(dists);
			if(estacao.getAreas() != null){
				int i = 0;
				areasSelecionadas = new Area[estacao.getAreas().size()];
				for (Area reg : estacao.getAreas()) {
					areasSelecionadas[i++] = reg;
				}
			}
		}

		if (operacao.equals("ALTERAR") || operacao.equals("NOVO")){		
			areas = areaService.pesquisar(distritos);
		}
	}
	
	public void carregarAreas() {
		if(estacao.getDistrito()==null){
			areas = null;
		}else{
			ArrayList<Distrito> dists = new ArrayList<Distrito>();
			dists.add(estacao.getDistrito());
			areas = areaService.pesquisar(dists);
		}
	}  
	
	public void gravar(ActionEvent actionEvent) {
		prepararAreas();
		estacao = estacaoService.salvar(estacao); 
		if (operacao.equals("NOVO")) {
			estacao = null;
			areasSelecionadas = null;
			infoMsg(ResourceBundle.getMessage("estacaoSalvar")+ ".", MSG_TITULO);
		}else{
			infoMsg(ResourceBundle.getMessage("estacaoAlterar")+ ".", MSG_TITULO);
		}
    }

	private void prepararAreas() {
		if (areasSelecionadas.length > 0) {
			List<Area> regs  = new ArrayList<Area>();
			for (int i = 0; i < areasSelecionadas.length; i++) {
				regs.add(areasSelecionadas[i]);
			}
			estacao.setAreas(regs);
		}
	}

	public String voltar() {
		return "consultarEstacao?faces-redirect=true";
	}

	public Estacao getEstacao() {
		if (estacao == null) {
			estacao = (Estacao) getFlashScope().get("estacao");
		}
		return estacao;
	}

	public void setEstacao(Estacao estacao) {
		this.estacao = estacao;
		getFlashScope().put("estacao", estacao);
	}

	public List<Distrito> getDistritos() {
		return distritos;
	}

	public void setDistritos(List<Distrito> distritos) {
		this.distritos = distritos;
	}

	public Boolean getMultiDistrito() {
		return multiDistrito;
	}

	public void setMultiDistrito(Boolean multiDistrito) {
		this.multiDistrito = multiDistrito;
	}

	public List<Area> getAreas() {
		return areas;
	}

	public void setAreas(List<Area> areas) {
		this.areas = areas;
	}

	public Area[] getAreasSelecionadas() {
		return areasSelecionadas;
	}

	public void setAreasSelecionadas(Area[] areasSelecionadas) {
		this.areasSelecionadas = areasSelecionadas;
	}

	public String getOperacao() {
		if (operacao == null) {
			operacao = (String) getFlashScope().get("operacao");
		}
		return operacao;
	}

	public void setOperacao(String operacao) {
		this.operacao = operacao;
		getFlashScope().put("operacao", operacao);
	}
}

sistemasai/src/com/agrosolutions/sai/view/ConsultarClimaBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Area;
import com.agrosolutions.sai.model.Clima;
import com.agrosolutions.sai.model.Mes;
import com.agrosolutions.sai.model.TipoPerfil;
import com.agrosolutions.sai.service.ClimaService;
import com.agrosolutions.sai.service.IrriganteService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Consultar Clima
* 
* @since   : Mar 08, 2011, 19:23:20 AM
* @author  : rpf1404@gmail.com
*/

@Component("consultarClimaBean")
@Scope("session")
public class ConsultarClimaBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = -5658220567105554889L;

	public static Logger logger = Logger.getLogger(ConsultarClimaBean.class);

	public static final String MSG_TITULO = "Consultar Clima";

	@Autowired
	private ClimaService climaService;
	@Autowired
	private IrriganteService irriganteService;
	
	private List<Clima> climas;
	private Area area;
	private Integer ano;
	private Mes mes;

	
	public void carregarDadosIniciais() {
		if (area == null && getUsuarioLogado().getPerfil().getTipo().equals(TipoPerfil.Irrigante)) {
			area = irriganteService.pesquisarPorUsuario(getUsuarioLogado()).getArea();
		}

		if (mes == null && ano == null) {
			Calendar data = new GregorianCalendar();
			data.setTime(new Date());
			ano = data.get(Calendar.YEAR);
			for (Mes m : Mes.values()) {
				if (m.ordinal() == data.get(Calendar.MONTH)){
					mes = m;		
				}
			}
		}
		if (mes != null && ano != null) {
			Calendar dataIni = new GregorianCalendar();
			Calendar dataFim = new GregorianCalendar();
			dataIni.set(ano, mes.ordinal(), 1);
			dataFim.set(ano, mes.ordinal()+1, 1);
			
			climas = climaService.pesquisarPorPeriodo(area, dataIni.getTime(), dataFim.getTime());
			if (climas.isEmpty()) {
				infoMsg(ResourceBundle.getMessage("climaExcluir")+ ".", null);
			}
		}
	}

    public String cadastro() {
		return "cadastrarClima?faces-redirect=true";
	}

	public String voltar() {
		if (getUsuarioLogado().getPerfil().getTipo().equals(TipoPerfil.Irrigante)) {
			return "/homeIrrigante?faces-redirect=true";
		} else {
			return "consultarArea?faces-redirect=true";
		}
	}

	public List<Clima> getClimas() {
		return climas;
	}

	public void setClimas(List<Clima> climas) {
		this.climas = climas;
	}

	public Area getArea() {
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public Mes[] getMeses() {
		return Mes.values();
	}

	public Integer getAno() {
		return ano;
	}

	public void setAno(Integer ano) {
		this.ano = ano;
	}

	public Mes getMes() {
		return mes;
	}

	public void setMes(Mes mes) {
		this.mes = mes;
	}

}

sistemasai/WebContent/paginas/distrito/consultarClima.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="../../WEB-INF/templates/page.xhtml"
	  xmlns="http://www.w3.org/1999/xhtml"     
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
	  xmlns:h="http://java.sun.com/jsf/html"
 	  xmlns:c="http://java.sun.com/jsp/jstl/core"
	  xmlns:p="http://primefaces.org/ui" >
	<ui:define name="content">
		<f:metadata>
		   <f:event type="preRenderView" listener="#{consultarClimaBean.carregarDadosIniciais}" />	
		</f:metadata>
		
		<h:form id="frmConsultarClima" styleClass="formularios box-border" prependId="false">
				
			<p:messages showDetail="false" autoUpdate="true"/>
			<div class="bc cinzaclaro barra">
        		<div class="titulo" >
					#{bundle.consultarClimaArea}<h:outputText value="#{consultarClimaBean.area.nome}" />
				</div>
				<div class="botoes">
					<p:commandButton id="btNovo" value="#{bundle.addClima}" action="#{consultarClimaBean.cadastro}" ajax="true" styleClass="btn primary" rendered="#{LoginBean.anyGranted('ROLE_CADASTRAR_CLIMA')}">
						<f:setPropertyActionListener value="" target="#{cadastrarClimaBean.clima}" />  
					</p:commandButton>
					<p:commandButton id="btVoltar" value="#{bundle.voltar}" action="#{consultarClimaBean.voltar}" styleClass="btn primary" immediate="true" />
				</div>
			</div>	
			<div class="b2 cinzaclaro"></div>
			<div class="b1 cinzaclaro"></div>
			<br />
			<div class="row">
				<div class="span2 clear">
					<label for="mes" class="block"><b>#{bundle.mes}:</b></label>
					<h:selectOneMenu id="mes" value="#{consultarClimaBean.mes}" title="#{bundle.selecioneMes}" style="width: 150px;">  
	           			<f:selectItems var="tipo" itemLabel="#{tipo.descricao}" itemValue="#{tipo}" value="#{consultarClimaBean.meses}"  />
						<p:ajax update=":frmConsultarClima" event="change" process="@this" /> 
	        		</h:selectOneMenu>							
				</div>
				<div class="span2">
					<label for="ano" class="block"><b>#{bundle.ano}:</b></label>							
					<p:spinner id="ano" value="#{consultarClimaBean.ano}" min="1950" style="margin-right: 0px;" size="4">
						<p:ajax update=":frmConsultarClima" process="@this" />  
           			</p:spinner>  							
				</div>
				<div class="span2 clear">
					<p:spacer height="10"/>
				</div>
				<div class="span2 clear">
					<p:dataGrid var="clima" value="#{consultarClimaBean.climas}" emptyMessage="#{bundle.climaNaoExiste}" columns="#{consultarClimaBean.climas.size() &lt; 4?consultarClimaBean.climas.size():4}">
						<p:column>
							<p:panel footer="ETo = #{clima.etoCalculado}(mm/dia) " styleClass="pnlClima">
								<f:facet name="header">
						            <p:commandLink action="#{consultarClimaBean.cadastro}" title="#{bundle.alterarClima}" value="#{clima.dia}">  
										<f:setPropertyActionListener value="#{clima}" target="#{cadastrarClimaBean.clima}" />  
						                <f:setPropertyActionListener value="ALTERAR" target="#{cadastrarClimaBean.operacao}" />  
				        		    </p:commandLink>  				         
				    	        
        						</f:facet>
								<h:panelGrid columns="3">
									<p:outputPanel>
										<label for="tempMin" class="block" style="font-size:10px;"><b>#{bundle.tmin}</b></label>							
							            <h:outputText id="tempMin" value="#{clima.tempMin}"  style="text-align:center;">
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="1"/>
										</h:outputText>
									</p:outputPanel>     
									<p:outputPanel>
										<label for="tempMax" class="block" style="font-size:10px;"><b>#{bundle.tmax}</b></label>							
							            <h:outputText id="tempMax" value="#{clima.tempMax}" >
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="1"/>
										</h:outputText>
									</p:outputPanel>     
									<p:outputPanel>
										<label for="tempMed" class="block" style="font-size:10px;"><b>#{bundle.tmed}</b></label>							
							            <h:outputText id="tempMed" value="#{clima.tempMed}"  style="text-align:center;">
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="1"/>
										</h:outputText>
									</p:outputPanel>     
									<p:outputPanel>
										<label for="umidadeMin" class="block" style="font-size:10px;"><b>#{bundle.umidMin}</b></label>							
							            <h:outputText id="umidadeMin" value="#{clima.umidadeMin}" >
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="0"/>
										</h:outputText>
									</p:outputPanel>     
									<p:outputPanel>
										<label for="umidadeMax" class="block" style="font-size:10px;"><b>#{bundle.umidMax}</b></label>							
							            <h:outputText id="umidadeMax" value="#{clima.umidadeMax}" >
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="0"/>
										</h:outputText>
									</p:outputPanel>     
									<p:outputPanel>
										<label for="umidadeMed" class="block" style="font-size:10px;"><b>#{bundle.umidMed}</b></label>							
							            <h:outputText id="umidadeMed" value="#{clima.umidadeMed}" >
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="0"/>
										</h:outputText>
									</p:outputPanel>     
									<p:outputPanel>
										<label for="vento" class="block" style="font-size:10px;"><b>#{bundle.ventMS}</b></label>							
							            <h:outputText id="vento" value="#{clima.vento}" >
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="0"/>
										</h:outputText>
									</p:outputPanel>     
									<p:outputPanel>
										<label for="rajada" class="block" style="font-size:10px;"><b>#{bundle.rajada}</b></label>							
							            <h:outputText id="rajada" value="#{clima.ventoRajada}" >
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="0"/>
										</h:outputText>
									</p:outputPanel>     
									<p:outputPanel>
										<label for="chuva" class="block" style="font-size:10px;"><b>#{bundle.precipitacao}</b></label>							
							            <h:outputText id="chuva" value="#{clima.chuva}" >  
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="1"/>
										</h:outputText>   
									</p:outputPanel>     
									<p:outputPanel>
										<label for="rad" class="block" style="font-size:10px;"><b>#{bundle.rad}</b></label>							
							            <h:outputText id="rad" value="#{clima.radiacao}" >  
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="1"/>
										</h:outputText>   
									</p:outputPanel>     
									<p:outputPanel>
										<label for="radL" class="block" style="font-size:10px;"><b>#{bundle.radLiq}</b></label>							
							            <h:outputText id="radL" value="#{clima.radLiquida}" >  
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="1"/>
										</h:outputText>   
									</p:outputPanel>     
									<p:outputPanel>
										<label for="pressao" class="block" style="font-size:10px;"><b>#{bundle.pressaoMed}</b></label>							
							            <h:outputText id="pressao" value="#{clima.pressaoMed}" >  
							    			<f:convertNumber locale="pt_BR" maxFractionDigits="1"/>
										</h:outputText>   
									</p:outputPanel>     
								</h:panelGrid>
							</p:panel>
						</p:column>
					</p:dataGrid>
				</div>
			</div>				
		</h:form>
	</ui:define>
</ui:composition>

sistemasai/WebContent/paginas/distrito/importarClima.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
	  xmlns:sec="http://www.springframework.org/security/facelets/tags" >

	<h:form id="frmImportarClima" >
		<p:dialog id="modalDialogImportarClima" header="#{bundle.importarClima}" widgetVar="ic" modal="true" height="150" width="260" >  
			<p:messages id="msg" showDetail="false" autoUpdate="true" for="textOnly" display="text"/>
			<div class="span2 clear">
				<label for="estacao" class="block"><b>#{bundle.estacao}:</b></label>
				<h:selectOneMenu id="estacao" value="#{importarClimaBean.estacao}" converter="estacaoConverter" title="#{bundle.selecioneEstacaoEspecifica}" style="width: 205px;" >  
           			<f:selectItems var="estacao" itemLabel="#{estacao.nome}" itemValue="#{estacao}" value="#{importarClimaBean.estacoes}"  />
					<p:ajax process="@this" /> 
        		</h:selectOneMenu>							
			</div>
			<br />
			<br />
			<h:panelGrid columns="2">
				<p:fileUpload fileUploadListener="#{importarClimaBean.importarClima}" rendered="#{LoginBean.anyGranted('ROLE_IMPORTAR_CLIMA')}"
		            mode="advanced" showButtons="true" label="#{bundle.importarClima}"  oncomplete="ic.hide()"
		            auto="true"  
		            sizeLimit="20000000"   
		            allowTypes="/(\.|\/)(dat|html|csv|CSV)$/"/> 				
	       		<p:commandButton value="#{bundle.cancelar}" onclick="ic.hide()" type="button" styleClass="btn cancel" />
 			</h:panelGrid>
 		</p:dialog>
	</h:form>
</html>

sistemasai/WebContent/paginas/distrito/importarCoordenadas.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
	  xmlns:sec="http://www.springframework.org/security/facelets/tags" >

	<h:form id="frmImportarCoordenadas" >
		<p:dialog id="modalDialogImportarClima" header="#{bundle.importarCoordenadas}" widgetVar="ic" modal="true" height="150" width="260" >  
			<p:messages id="msg" showDetail="false" autoUpdate="true" for="textOnly" display="text"/>
			
			<h:panelGrid columns="2">
				<p:fileUpload fileUploadListener="#{importarCoordenadasBean.importarCoordenadas}" rendered="#{LoginBean.anyGranted('ROLE_IMPORTAR_CLIMA')}"
		            mode="advanced" showButtons="true" label="#{bundle.importarCoordenadas}"  oncomplete="ic.hide()"
		            auto="true"  
		            sizeLimit="100000000"   
		            allowTypes="/(\.|\/)(kml|dat|html)$/"/>				
	       		<p:commandButton value="#{bundle.cancelar}" onclick="ic.hide()" type="button" styleClass="btn cancel" />
 			</h:panelGrid>
 		</p:dialog>
	</h:form>
</html>