sistemasai/src/com/agrosolutions/sai/view/CadastrarAduboBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;

import javax.faces.event.ActionEvent;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Adubo;
import com.agrosolutions.sai.service.AduboService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Cadastrar Adubo
* 
* @since   : Jan 27, 2012, 05:23:20 AM
* @author  : raphael.ferreira@ivia.com.br
*/

@Component("cadastrarAduboBean")
@Scope("session")
public class CadastrarAduboBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = -3282700631180475987L;

	public static Logger logger = Logger.getLogger(CadastrarAduboBean.class);

	public static final String MSG_TITULO = "Cadastro de Adubo";

	@Autowired
	private AduboService aduboService;
	
	private Adubo adubo;
	private String operacao;
	
	public void carregarDadosIniciais() {
		operacao = getOperacao();
		adubo = getAdubo();
		
		if (operacao.equals("NOVO") && adubo == null) {
			adubo = new Adubo();
		}
	}
	
	public void gravar(ActionEvent actionEvent) {
		adubo = aduboService.salvar(adubo); 
		if (operacao.equals("NOVO")) {
		adubo = null;
			infoMsg(ResourceBundle.getMessage("aduboSalvar")+ ".", MSG_TITULO);
		}else{
			infoMsg(ResourceBundle.getMessage("aduboAlterar")+ ".", MSG_TITULO);
		}
	}
	public String voltar() {
		return "consultarAdubo?faces-redirect=true";
	}

	public Adubo getAdubo() {
		if (adubo == null) {
			adubo = (Adubo) getFlashScope().get("adubo");
		}
		return adubo;
	}

	public void setAdubo(Adubo adubo) {
		this.adubo = adubo;
		getFlashScope().put("adubo", adubo);
	}

	public String getOperacao() {
		if (operacao == null) {
			operacao = (String) getFlashScope().get("operacao");
		}
		return operacao;
	}

	public void setOperacao(String operacao) {
		this.operacao = operacao;
		getFlashScope().put("operacao", operacao);
	}
}

sistemasai/src/com/agrosolutions/sai/view/CadastrarAtividadeBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Atividade;
import com.agrosolutions.sai.service.AtividadeService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Cadastrar Atividade
* 
* @since   : Jan 27, 2012, 03:23:20 AM
* @author  : raphael.ferreira@ivia.com.br
*/

@Component("cadastrarAtividadeBean")
@Scope("session")
public class CadastrarAtividadeBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = 8666560690340386588L;

	public static Logger logger = Logger.getLogger(CadastrarAtividadeBean.class);

	public static final String MSG_TITULO = "Cadastro de Atividade";

	@Autowired
	private AtividadeService atividadeService;
	
	private Atividade atividade;
	private Boolean cadastroCultura;
	private String operacao;
	
	public void carregarDadosIniciais() {
		operacao = getOperacao();
		atividade = getAtividade();
		cadastroCultura = getCadastroCultura();
		
		if (getOperacao().equals("NOVO") && getAtividade() == null) {
			atividade = new Atividade();
		}
	}
	
	public String gravar() {
		String volta = null;
		atividade = atividadeService.salvar(atividade); 

		if (operacao.equals("NOVO")) {
			atividade = new Atividade();
			infoMsg(ResourceBundle.getMessage("atividadeSalvar")+ ".", MSG_TITULO);
		}else{
			infoMsg(ResourceBundle.getMessage("atividadeAlterar")+ ".", MSG_TITULO);
		}

		if (cadastroCultura != null && cadastroCultura) {
			cadastroCultura = false;
			volta = "cadastrarCultura";
		}
		
		return volta;
}

	public String voltar() {
		String volta;
		volta = "consultarAtividade?faces-redirect=true";

		if (cadastroCultura != null && cadastroCultura) {
			cadastroCultura = false;
			volta = "cadastrarCultura?faces-redirect=true";
		}
		
		return volta;
	}

	public Atividade getAtividade() {
		if (atividade==null){
			atividade = (Atividade) getFlashScope().get("atividade");
		}
		return atividade;
	}

	public void setAtividade(Atividade atividade) {
		this.atividade = atividade;
		getFlashScope().put("atividade", atividade);
	}

	public Boolean getCadastroCultura() {
		if (cadastroCultura==null){
			cadastroCultura = (Boolean) getFlashScope().get("cadastroCultura");
		}
		return cadastroCultura;
	}

	public void setCadastroCultura(Boolean cadastroCultura) {
		this.cadastroCultura = cadastroCultura;
		getFlashScope().put("cadastroCultura", cadastroCultura);
	}

	public String getOperacao() {
		if (operacao == null) {
			operacao = (String) getFlashScope().get("operacao");
		}
		return operacao;
	}

	public void setOperacao(String operacao) {
		this.operacao = operacao;
		getFlashScope().put("operacao", operacao);
	}
}

sistemasai/src/com/agrosolutions/sai/view/CadastrarBombaBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;
import java.util.List;

import javax.faces.event.ActionEvent;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.AcionamentoBomba;
import com.agrosolutions.sai.model.Bomba;
import com.agrosolutions.sai.model.Fabricante;
import com.agrosolutions.sai.model.TipoBomba;
import com.agrosolutions.sai.model.TipoFabricante;
import com.agrosolutions.sai.service.BombaService;
import com.agrosolutions.sai.service.FabricanteService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Cadastrar Bomba
* 
* @since   : Jan 06, 2012, 22:10:20 AM
* @author  : raphael.ferreira@ivia.com.br
*/

@Component("cadastrarBombaBean")
@Scope("session")
public class CadastrarBombaBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = -425450556876285711L;

	public static Logger logger = Logger.getLogger(CadastrarBombaBean.class);

	public static final String MSG_TITULO = "Cadastro de Bomba";

	@Autowired
	private BombaService bombaService;
	@Autowired
	private FabricanteService fabricanteService;
	
	private Bomba bomba;
	private List<Fabricante> fabricantes;
	private Fabricante fabricante;
	private String operacao;
	
	public void carregarDadosIniciais() {
		operacao = getOperacao();
		bomba = getBomba();
		fabricante = getFabricante();
		
		if (operacao.equals("NOVO") && bomba == null) {
			bomba = new Bomba();
		}
		if (fabricantes == null) {
			fabricantes = fabricanteService.pesquisar(TipoFabricante.Bomba);
		}
		if (fabricante != null) {
			bomba.setFabricante(fabricante);
			fabricante = null;
		}
	}
	
	public void gravar(ActionEvent actionEvent) {
		bomba = bombaService.salvar(bomba);
		if (operacao.equals("NOVO")) {
			bomba = null;
			infoMsg(ResourceBundle.getMessage("bombaSalvar")+ ".", MSG_TITULO);
		}else{
			infoMsg(ResourceBundle.getMessage("bombaAlterar")+ ".", MSG_TITULO);
		}
    }

	public String novoFabricante() {
		return "cadastrarFabricante?faces-redirect=true";
	}

	public String voltar() {
		return "consultarBomba?faces-redirect=true";
	}
	
	public Bomba getBomba() {
		if (bomba == null) {
			bomba = (Bomba) getFlashScope().get("bomba");
		}
		return bomba;
	}

	public void setBomba(Bomba bomba) {
		this.bomba = bomba;
		getFlashScope().put("bomba", bomba);
	}

	public List<Fabricante> getFabricantes() {
		return fabricantes;
	}

	public void setFabricantes(List<Fabricante> fabricantes) {
		this.fabricantes = fabricantes;
	}

	public Fabricante getFabricante() {
		if (fabricante == null) {
			fabricante = (Fabricante) getFlashScope().get("fabricante");
		}
		return fabricante;
	}

	public void setFabricante(Fabricante fabricante) {
		this.fabricante = fabricante;
		getFlashScope().put("fabricante", fabricante);
		
	}

	public TipoBomba[] getTipos() {
		return TipoBomba.values();
	}
	public AcionamentoBomba[] getAcionamentos() {
		return AcionamentoBomba.values();
	}

	public String getOperacao() {
		if (operacao == null) {
			operacao = (String) getFlashScope().get("operacao");
		}
		return operacao;
	}

	public void setOperacao(String operacao) {
		this.operacao = operacao;
		getFlashScope().put("operacao", operacao);
	}
}

sistemasai/src/com/agrosolutions/sai/view/CadastrarCulturaBean.java
package com.agrosolutions.sai.view;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.Serializable;
import java.util.List;

import org.apache.log4j.Logger;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Atividade;
import com.agrosolutions.sai.model.Cultura;
import com.agrosolutions.sai.service.AtividadeService;
import com.agrosolutions.sai.service.CulturaService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Cadastrar Cultura
* 
* @since   : Jan 17, 2012, 22:00:20 AM
* @author  : rpf1404@gmail.com
*/

@Component("cadastrarCulturaBean")
@Scope("session")
public class CadastrarCulturaBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = 4524560196224731215L;

	public static Logger logger = Logger.getLogger(CadastrarCulturaBean.class);

	public static final String MSG_TITULO = "Cadastro de Cultura";

	@Autowired
	private CulturaService culturaService;
	@Autowired
	private AtividadeService atividadeService;
	
	private Cultura cultura;
	private Boolean cadastroVariedade;
	private Boolean cadastroCultivo;
	private List<Atividade> atividades;
	private Atividade atividade;
	
	private String operacao;

	public void carregarDadosIniciais() {
		operacao = getOperacao();
		cultura = getCultura();
		cadastroCultivo = getCadastroCultivo();
		cadastroVariedade = getCadastroVariedade();
		atividade = getAtividade();
		
		if (operacao.equals("NOVO") && cultura == null) {
			cultura = new Cultura();
		}
		if (operacao.equals("ALTERAR") || operacao.equals("NOVO")){		
			//Se tiver atividade preenchida foi recem cadastrada e deve ser setada no objeto.
			if (atividade != null) {
				cultura.setAtividade(atividade);
				atividade = null;
			}
		}
		atividades = atividadeService.obterTodos();
		
	}

	public String novaAtividade() {
		return "cadastrarAtividade";
	}

	public String gravar() {
		String volta = null;
		cultura = culturaService.salvar(cultura); 

		if (operacao.equals("NOVO")) {
			cultura = null;
			infoMsg(ResourceBundle.getMessage("culturaSalvar")+ ".", MSG_TITULO);
		}else{
			infoMsg(ResourceBundle.getMessage("culturaAlterar")+ ".", MSG_TITULO);
		}
		
		if (cadastroCultivo != null && cadastroCultivo) {
			cadastroCultivo = false;
			volta = "cadastrarCultivo?faces-redirect=true";
		}
		if (cadastroVariedade != null && cadastroVariedade) {
			cadastroVariedade = false;
			volta = "cadastrarVariedade?faces-redirect=true";
		}
		
		return volta;
		
    }
    public void uploadImage(FileUploadEvent event) {
    	final String caminho = System.getProperty("imagem_sai");

		try{
	    	UploadedFile arq = event.getFile();
			InputStream in = new BufferedInputStream(arq.getInputstream());
			File file = new File(caminho + File.separator + arq.getFileName());
			FileOutputStream fout = new FileOutputStream(file);
			 
			while(in.available() != 0){
				fout.write(in.read());
			}
			fout.close();
    		cultura.setImage(file.getName());
    		infoMsg("Image foi carregada.", null);
		}
		catch(Exception ex){
			ex.printStackTrace();
		}
    }
	public String voltar() {
		String volta = "consultarCultura?faces-redirect=true";

		if (cadastroCultivo != null && cadastroCultivo) {
			cadastroCultivo = false;
			volta = "cadastrarCultivo?faces-redirect=true";
		}
		if (cadastroVariedade != null && cadastroVariedade) {
			cadastroVariedade = false;
			volta = "cadastrarVariedade?faces-redirect=true";
		}
		
		return volta;
	}

	public Cultura getCultura() {
		if (cultura == null) {
			cultura = (Cultura) getFlashScope().get("cultura");
		}
		return cultura;
	}

	public void setCultura(Cultura cultura) {
		this.cultura = cultura;
		getFlashScope().put("cultura", cultura);
	}

	public Boolean getCadastroVariedade() {
		if (cadastroVariedade == null) {
			cadastroVariedade = (Boolean) getFlashScope().get("cadastroVariedade");
		}
		return cadastroVariedade;
	}

	public void setCadastroVariedade(Boolean cadastroVariedade) {
		this.cadastroVariedade = cadastroVariedade;
		getFlashScope().put("cadastroVariedade", cadastroVariedade);
	}

	public Boolean getCadastroCultivo() {
		if (cadastroCultivo == null) {
			cadastroCultivo = (Boolean) getFlashScope().get("cadastroCultivo");
		}
		return cadastroCultivo;
	}

	public void setCadastroCultivo(Boolean cadastroCultivo) {
		this.cadastroCultivo = cadastroCultivo;
		getFlashScope().put("cadastroCultivo", cadastroCultivo);
	}

	public String getOperacao() {
		if (operacao == null) {
			operacao = (String) getFlashScope().get("operacao");
		}
		return operacao;
	}

	public void setOperacao(String operacao) {
		this.operacao = operacao;
		getFlashScope().put("operacao", operacao);
	}

	public List<Atividade> getAtividades() {
		return atividades;
	}

	public void setAtividades(List<Atividade> atividades) {
		this.atividades = atividades;
	}

	public Atividade getAtividade() {
		if (atividade == null) {
			atividade = (Atividade) getFlashScope().get("atividade");
		}
		return atividade;
	}

	public void setAtividade(Atividade atividade) {
		this.atividade = atividade;
		getFlashScope().put("atividade", atividade);
	}

}

sistemasai/src/com/agrosolutions/sai/view/CadastrarDefensivoBean.java
package com.agrosolutions.sai.view;

import java.io.Serializable;

import javax.faces.event.ActionEvent;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.agrosolutions.sai.model.Defensivo;
import com.agrosolutions.sai.service.DefensivoService;
import com.agrosolutions.sai.util.ResourceBundle;

/**
* Use case : Cadastrar Defensivo
* 
* @since   : Jan 27, 2012, 05:23:20 AM
* @author  : raphael.ferreira@ivia.com.br
*/

@Component("cadastrarDefensivoBean")
@Scope("session")
public class CadastrarDefensivoBean extends ManagerBean implements Serializable {

	private static final long serialVersionUID = 2953730849500946608L;

	public static Logger logger = Logger.getLogger(CadastrarDefensivoBean.class);

	public static final String MSG_TITULO = "Cadastro de Defensivo";

	@Autowired
	private DefensivoService defensivoService;
	
	private Defensivo defensivo;
	private String operacao;
	
	public void carregarDadosIniciais() {
		operacao = getOperacao();
		defensivo = getDefensivo();
		
		if (operacao.equals("NOVO") && defensivo == null) {
			defensivo = new Defensivo();
		}
	}
	
	public void gravar(ActionEvent actionEvent) {
		defensivo = defensivoService.salvar(defensivo); 
		if (operacao.equals("NOVO")) {
		defensivo = null;
			infoMsg(ResourceBundle.getMessage("defensivoSalvar")+ ".", MSG_TITULO);
		}else{
			infoMsg(ResourceBundle.getMessage("defensivoAlterar")+ ".", MSG_TITULO);
		}
	}

	public String voltar() {
		return "consultarDefensivo?faces-redirect=true";
	}

	public Defensivo getDefensivo() {
		if (defensivo == null) {
			defensivo = (Defensivo) getFlashScope().get("defensivo");
		}
		return defensivo;
	}

	public void setDefensivo(Defensivo defensivo) {
		this.defensivo = defensivo;
		getFlashScope().put("defensivo", defensivo);
	}

	public String getOperacao() {
		if (operacao == null) {
			operacao = (String) getFlashScope().get("operacao");
		}
		return operacao;
	}

	public void setOperacao(String operacao) {
		this.operacao = operacao;
		getFlashScope().put("operacao", operacao);
	}
}

sistemasai/WebContent/paginas/tabela/cadastrarAdubo.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="../../WEB-INF/templates/page.xhtml"
		xmlns="http://www.w3.org/1999/xhtml"     
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:c="http://java.sun.com/jsp/jstl/core"
	  	xmlns:p="http://primefaces.org/ui" >
		
	<ui:define name="content">
		
		<f:metadata>
		   <f:event type="preRenderView" listener="#{cadastrarAduboBean.carregarDadosIniciais}" />	
		</f:metadata>			
		
		<h:form id="frmCadastrarAdubo" styleClass="formularios box-border" prependId="false">
			<p:messages showDetail="false" autoUpdate="true" for="textOnly" display="text"/>
			<div class="bc cinzaclaro barra">
        		<div class="titulo" >
					#{bundle.cadastroAdubo}
				</div>
				<div class="botoes">
					<p:commandButton id="btSalvar" actionListener="#{cadastrarAduboBean.gravar}" value="#{bundle.salvar}" styleClass="btn success" update=":frmCadastrarAdubo" process="@form" rendered="#{cadastrarAduboBean.operacao ne 'VER'}"/>
					<p:commandButton id="btVoltar" value="#{bundle.voltar}" action="#{cadastrarAduboBean.voltar}" styleClass="btn primary" immediate="true" >
		                <f:setPropertyActionListener value="" target="#{consultarAduboBean.adubos}" />  
					</p:commandButton>    
				</div>
			</div>	
			<div class="b2 cinzaclaro"></div>
			<div class="b1 cinzaclaro"></div>
			<br />
			<div class="row cadastro">		
				<div class="col-direita">
					<div class="row">
						<div class="span2 clear">
							<label for="nome"><b>#{bundle.nome}:</b></label><label class="label-required">*</label>
							<p:inputText styleClass="block" id="nome" required="true" requiredMessage="#{bundle.nomeObrigatorio}" title="#{bundle.nomeAdubo}" maxlength="255" value="#{cadastrarAduboBean.adubo.nome}" size="80" disabled="#{cadastrarAduboBean.operacao eq 'VER'}"/>
						</div>
						<div class="span2 clear">
							<label for="observacao" class="block"><b>#{bundle.observacao}:</b></label>
							<p:inputTextarea id="observacao" cols="62" rows="4" autoResize="false" maxlength="800" value="#{cadastrarAduboBean.adubo.observacao}" disabled="#{cadastrarAduboBean.operacao eq 'VER'}"/>							
						</div>
						
					</div>
				</div>
			</div>				
		</h:form>
	</ui:define>
</ui:composition>

sistemasai/WebContent/paginas/tabela/cadastrarValvula.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition template="../../WEB-INF/templates/page.xhtml"
		xmlns="http://www.w3.org/1999/xhtml"     
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:c="http://java.sun.com/jsp/jstl/core"
		xmlns:p="http://primefaces.org/ui" >
		
	<ui:define name="content">
	    <script type="text/javascript" src="#{facesContext.externalContext.requestContextPath}/js/jquery.maskMoney.0.2-adaptado.js"></script>
	    <script type="text/javascript" src="#{facesContext.externalContext.requestContextPath}/js/util.js"></script>
		<f:metadata>
		   <f:event type="preRenderView" listener="#{cadastrarValvulaBean.carregarDadosIniciais}" />	
		</f:metadata>			
		
		<h:form id="frmCadastrarValvula" styleClass="formularios box-border" prependId="false">
			<p:messages showDetail="false" autoUpdate="true" for="textOnly" display="text"/>
			<div class="bc cinzaclaro barra">
        		<div class="titulo" >
					#{bundle.cadastroValvula}
				</div>
				<div class="botoes">
					<p:commandButton id="btSalvar" actionListener="#{cadastrarValvulaBean.gravar}" value="#{bundle.salvar}" styleClass="btn success" update=":frmCadastrarValvula" process="@form" rendered="#{cadastrarValvulaBean.operacao ne 'VER'}"/>
					<p:commandButton id="btVoltar" value="#{bundle.voltar}" action="#{cadastrarValvulaBean.voltar}" styleClass="btn primary" immediate="true" />
				</div>
			</div>	
			<div class="b2 cinzaclaro"></div>
			<div class="b1 cinzaclaro"></div>
			<br />
			
			<div class="row cadastro">		
				<div class="col-direita">
					<div class="row">
						<div class="span2 clear">
							<label for="fabricante" class="block"><b>#{bundle.fabricante}:</b></label>							
							<h:selectOneMenu id="fabricante" value="#{cadastrarValvulaBean.valvula.fabricante}" converter="fabricanteConverter" title="#{bundle.selecioneFabricante}" style="width: 189px;" disabled="#{cadastrarValvulaBean.operacao eq 'VER'}">  
		            			<f:selectItems var="fabricante" itemLabel="#{fabricante.nome}" itemValue="#{fabricante}" value="#{cadastrarValvulaBean.fabricantes}"  />
			        		</h:selectOneMenu>							
							<p:commandButton id="btNovo" value="#{bundle.novo}" action="#{cadastrarValvulaBean.novoFabricante}" styleClass="btn small" rendered="#{LoginBean.anyGranted('ROLE_CADASTRAR_FABRICANTE')}" process="@form" disabled="#{cadastrarValvulaBean.operacao eq 'VER'}">
				                <f:setPropertyActionListener value="true" target="#{cadastrarFabricanteBean.cadastroValvula}" />  
								<f:setPropertyActionListener value="" target="#{cadastrarFabricanteBean.fabricante}" />  
							</p:commandButton>  
						</div>
						<div class="span2 clear">
							<label for="modelo"><b>#{bundle.modelo}:</b></label><label class="label-required">*</label>
							<p:inputText styleClass="block" style="width:415px;" id="modelo" required="true" requiredMessage="#{bundle.modeloObrigatorio}." title="#{bundle.modelo}" maxlength="255" value="#{cadastrarValvulaBean.valvula.modelo}" size="80" disabled="#{cadastrarValvulaBean.operacao eq 'VER'}"/>
						</div>
						<div class="span2 clear">
							<label for="tipo" class="block"><b>#{bundle.tipoValvula}:</b></label>							
							<h:selectOneMenu id="tipo" value="#{cadastrarValvulaBean.valvula.tipo}" title="#{bundle.selecioneTipoValvula}" style="width: 189px;" disabled="#{cadastrarValvulaBean.operacao eq 'VER'}">  
		            			<f:selectItems var="tipo" itemLabel="#{tipo.descricao}" itemValue="#{tipo}" value="#{cadastrarValvulaBean.tipos}"  />
			        		</h:selectOneMenu>							
						</div>
							<div class="span2 clear">
							<label for="vazao" class="block"><b>#{bundle.vazao}(m<sup>3</sup>/h):</b></label>
				            <p:inputText id="vazao" styleClass="money" value="#{cadastrarValvulaBean.valvula.vazao}" size="30" disabled="#{cadastrarValvulaBean.operacao eq 'VER'}">
				            	<f:validateLength maximum="15"/>
								<f:convertNumber locale="pt_BR" maxFractionDigits="1"/>
							</p:inputText>  
						</div>
					<div class="span2">
							<label for="pressao" class="block"><b>#{bundle.pressao}(Kgf/cm<sup>2</sup>):</b></label>
				            <p:inputText id="pressao" styleClass="money" value="#{cadastrarValvulaBean.valvula.pressao}" size="15" disabled="#{cadastrarValvulaBean.operacao eq 'VER'}">
				            	<f:validateLength maximum="15"/>
								<f:convertNumber locale="pt_BR" maxFractionDigits="1"/>
							</p:inputText>  
						</div>
					</div>
				</div>	
			</div>
			<script type="text/javascript">
				jQuery(document).ready(function($){
					$(".money").maskMoney(MASK_MONEY_MONETARIO);
				});		
			</script>
		</h:form>
	</ui:define>
</ui:composition>